# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Biographie
    url: /
    weight: 10
  - name: Papiers
    url: /#papers
    weight: 11
  - name: Talks
    url: /#talks
    weight: 12
  - name: Actualit√©s
    url: /#news
    weight: 13
  - name: Experiences
    url: experience/
    weight: 20
  - name: Projets
    url: projects/
    weight: 30
  - name: Ensegnements
    url: teaching/
    weight: 40
